language: android
sudo: required
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
licenses:
 - android-sdk-license-.+
script:
- "./gradlew clean build assemble -PdisablePreDex --stacktrace"